# vim: syntax=sshconfig textwidth=120 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent

stages:
  - test

variables: &global_vars
  VAR1: "my"
  VAR2: "balls"

.tpl: &tpl
  - echo "In template"

my-job:
  stage: test
  variables:
      <<: global_vars
      VAR1: "your"
  script:
    - *tpl
    - echo "In job"
    - echo "VAR1 ${VAR1}"
    - echo "VAR2 ${VAR2}"
