version: '2'

services:

  esn:
    extends:
      file: ../docker-compose-commons.yml
      service: esn
    build: ../../../
    command: ["sh", "start.sh"]
    links:
      - redis
      - mongo
      - sabre
      - elasticsearch
    environment:
      - PROVISION=true
      - JMAP_SERVER_HOST=jmap
      - JMAP_SERVER_PORT=80

  redis:
    extends:
      file: ../docker-compose-commons.yml
      service: redis

  mongo:
    extends:
      file: ../docker-compose-commons.yml
      service: mongo

  elasticsearch:
    extends:
      file: ../docker-compose-commons.yml
      service: elasticsearch

  sabre:
    extends:
      file: ../docker-compose-commons.yml
      service: sabre
    links:
      - mongo

  james:
    extends:
      file: ../docker-compose-commons.yml
      service: james
    links:
      - cassandra:cassandra
      - james_elastic:elasticsearch

  james_elastic:
    extends:
      file: ../docker-compose-commons.yml
      service: james_elastic

  cassandra:
    extends:
      file: ../docker-compose-commons.yml
      service: cassandra

  selenium-grid:
    image: elgalu/selenium:2.53.0p
    container_name: selenium-grid
    ports:
     - "4444:24444"
     - "5900:25900"
    environment:
      - VNC_PASSWORD=linagora
    links:
      - esn:esn_webapp
      - james:jmap