version: '2'

services:

  redis:
    extends:
      file: ../docker-compose-commons.yml
      service: redis

  rabbitmq:
    extends:
      file: ../docker-compose-commons.yml
      service: rabbitmq

  mongo:
    extends:
      file: ../docker-compose-commons.yml
      service: mongo

  elasticsearch:
    extends:
      file: ../docker-compose-commons.yml
      service: elasticsearch

  sabre:
    extends:
      file: ../docker-compose-commons.yml
      service: sabre
    image: linagora/esn-sabre-dev
    build:
      context: ${ESN_SABRE_PATH}
      dockerfile: Dockerfile.dev
    links:
      - mongo
    environment:
      - ESN_MONGO_DBNAME=esn
      - ESN_HOST=${ESN_HOST}
      - XDEBUG_CONFIG="remote_host=${ESN_HOST}"
    volumes:
      - ${ESN_SABRE_PATH}:/var/www/
      - ${ESN_SABRE_PATH}/config/20-xdebug.ini:/etc/php5/fpm/conf.d/20-xdebug.ini

  james:
    extends:
      file: ../docker-compose-commons.yml
      service: james
    links:
      - cassandra:cassandra
      - james_elastic:elasticsearch

  james_elastic:
    extends:
      file: ../docker-compose-commons.yml
      service: james_elastic

  cassandra:
    extends:
      file: ../docker-compose-commons.yml
      service: cassandra
