version: '2'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:2.6.5
    command: ["mongod", "--smallfiles"]
    ports:
      - "27017:27017"

  elasticsearch:
    image: linagora/esn-elasticsearch:latest
    ports:
      - "9200:9200"

  sabre:
    image: linagora/esn-sabre:latest
    ports:
      - "8001:80"
    links:
      - mongo
    environment:
      - SABRE_MONGO_HOST=mongo
      - SABRE_MONGO_PORT=27017
      - ESN_MONGO_HOST=mongo
      - ESN_MONGO_PORT=27017
      - ESN_MONGO_DBNAME=esn
      - ESN_HOST=${ESN_HOST}
      - ESN_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
